# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/414ff2b5-8a76-4df9-ad8b-2f7cd6dd57c7";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F692-19D3";
    fsType = "vfat";
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/666a612e-c2f6-4e37-8c34-c0402aa1e96d";
    fsType = "btrfs";
    options = ["subvol=@swap"];
  };

  boot.initrd.luks.devices."enclave".device = "/dev/disk/by-uuid/c05994a7-fd1f-4af4-8263-4c054604497d";

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    # useNetworkd = lib.mkDefault true;
    # defaultGateway6 = {
    #   address = "fe80::1";
    #   interface = "br0";
    # };
    # useDHCP = true;
    # enableIPv6 = true;

    # firewall = {
    #   allowedUDPPorts = [ 7769 ];
    # };
    # wireguard.interfaces = {
    #   wg0 = {
    #     ips = [ "198.8.59.68/27" "2a0f:85c1:31:dead:4::/48" ]; #HERE
    #     # listenPort = 7769;

    #     privateKeyFile = "/home/gabe/wireguard-keys/private";

    #     peers = [
    #       {
    #         publicKey = "MSDXVSk9GDSz2V1Un/B9GPCAv2aHhFzFYK35H1vRNkE="; # HERE
    #         allowedIPs = [ "198.8.59.65/32" "0.0.0.0/0" "::/0" ];

    #         endpoint = "198.8.59.1:7769"; #HERE

    #         persistentKeepalive = 25;
    #       }
    #     ];
    #   };
    # };
    bridges.br0.interfaces = ["enp5s0"];
    interfaces.br0.ipv4.addresses = [
      {
        address = "192.168.1.188";
        prefixLength = 24;
      }
    ];
    defaultGateway = "192.168.1.1";
    nameservers = [
      "9.9.9.10"
      "1.1.1.1"
    ];
  };

  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
